# Generated by Django 3.1.6 on 2021-02-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210214_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
