# Generated by Django 3.1.6 on 2021-02-28 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplymodel',
            name='apply_request',
            field=models.TextField(verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='jobapplymodel',
            name='apply_response',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='jobapplymodel',
            name='status',
            field=models.CharField(choices=[('Отправлен', 'Отправлен'), ('Отказ', 'Отказ'), ('Вас пригласили', 'Вас пригласили')], default='Отправлен', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='employment_status',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Freelance', 'Freelancer')], max_length=10, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='experience',
            field=models.CharField(max_length=100, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_location',
            field=models.CharField(max_length=120, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='responsibilities',
            field=models.TextField(verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ЗП'),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название вакансии'),
        ),
    ]
